[ wix-restaurants-java-sdk] added gzip encoder to getMenu endpoint
wix/wix-restaurants-java-sdk pull request #28
Opened 2021-12-26 19:39 UTC by guywix

2021-12-26 20:17 UTC, itayhewix requested changes

2021-12-26 20:17 UTC, itayhewix commented on wix-restaurants-java-client/src/main/java/com/wix/restaurants/DefaultWixRestaurantsClient.scala
> +    val request = Get(s"$apiUrl/organizations/$restaurantId/gzipMenu${queryLocationId}")
This url doesn’t exists

2021-12-26 20:18 UTC, guywix commented on wix-restaurants-java-client/src/main/java/com/wix/restaurants/DefaultWixRestaurantsClient.scala
> +    val request = Get(s"$apiUrl/organizations/$restaurantId/gzipMenu${queryLocationId}")
you right a mistake, fixed

2021-12-27 07:42 UTC, itayhewix approved these changes

2021-12-27 08:20 UTC, merged